version: "3.8"

services:
  # 1. DATABASE (Postgres)
  postgres:
    image: postgres:15-alpine
    container_name: kirimyos_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kirimyos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. REDIS (Queue)
  redis:
    image: redis:alpine
    container_name: kirimyos_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # 3. BACKEND (NestJS API)
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: kirimyos_api
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      # Config Redis di dalam container (hostnya bukan localhost, tapi nama service 'redis')
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WEBHOOK_URL: "https://n8n.teguhcoding.com/webhook/f04b43af-b9d3-410a-905b-56d0c0ad17eb"
    volumes:
      # Mount folder session WA biar kalau container mati, login WA gak ilang
      - ./wa_sessions:/app/wa_sessions
    restart: always

  # 4. FRONTEND (Next.js Dashboard)
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: kirimyos_web
    ports:
      - "3001:3000" # Kita mapping port 3001 di laptop ke 3000 di container
    depends_on:
      - api
    environment:
      # Karena ini Client Component, dia akses API lewat Browser user (localhost)
      NEXT_PUBLIC_API_URL: http://localhost:3000
    restart: always

volumes:
  postgres_data:
  redis_data:
